### ISSUE TITLE
試してみたいのですが、利用条件 (ライセンス) などありますでしょうか

### ISSUE THREAD

**Issue by moji29nabe** [tzmfreedom/apex_awsiot#1]
初めまして。
SF と AWS を連携してみたく、方法を検索していたところ apex_awsiot に出会いました。
試してみたいのですが、よろしければ apex_awsiot の利用条件/ライセンス (例えば MITラインセンスのような名称) を教えて頂けませんか 😄

**Comment by tzmfreedom** [comment]
@moji29nabe はじめまして。リポジトリ検索していただいてとても嬉しいです！
ライセンスは特に何も無いのでそのまま使うなり改変するなり自由に使ってくださいませ〜

古い記事ですがこちらも参照いただくと良いかもですー
https://blog.freedom-man.com/apex-awsiot

**Comment by moji29nabe** [comment]
@tzmfreedom ご回答ありがとうございます！
また、記事の共有も頂きありがとうございます 🙇 
早速試してみます
(本 issue は close させて頂きます)
